[package]
name = "bevy-jam5"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.14.0", features = ["dynamic_linking"]}
avian3d = "0.1"
bevy-inspector-egui = "0.25"
bevy_camera_extras = "0.9"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3